# Generated by Django 5.1.4 on 2026-08-04 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('articles', '0007_article_category_from_tree'),
        ('tenancy', '0002_bootstrap_default_site'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('view', 'Page view'), ('read_complete', 'Read to the end'), ('annotation_open', 'Annotation opened'), ('hotspot_open', 'Image hotspot opened'), ('media_play', 'Media played'), ('chapter_jump', 'Chapter jumped to'), ('outbound_click', 'Outbound link clicked'), ('share', 'Shared'), ('search', 'Search performed')], db_index=True, max_length=32)),
                ('target_id', models.CharField(blank=True, default='', max_length=100)),
                ('path', models.CharField(blank=True, default='', max_length=500)),
                ('referrer', models.CharField(blank=True, default='', max_length=500)),
                ('locale', models.CharField(blank=True, default='', max_length=10)),
                ('session', models.CharField(db_index=True, max_length=32)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('occurred_at', models.DateTimeField(db_index=True)),
                ('article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='articles.article')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenancy.site')),
            ],
            options={
                'ordering': ['-occurred_at', '-id'],
                'indexes': [models.Index(fields=['site', 'occurred_at'], name='analytics_c_site_id_6b0ec0_idx'), models.Index(fields=['article', 'name', 'occurred_at'], name='analytics_c_article_597e27_idx')],
            },
        ),
        migrations.CreateModel(
            name='DailyContentStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(db_index=True)),
                ('views', models.PositiveIntegerField(default=0)),
                ('unique_sessions', models.PositiveIntegerField(default=0)),
                ('reads_completed', models.PositiveIntegerField(default=0)),
                ('annotation_opens', models.PositiveIntegerField(default=0)),
                ('hotspot_opens', models.PositiveIntegerField(default=0)),
                ('media_plays', models.PositiveIntegerField(default=0)),
                ('outbound_clicks', models.PositiveIntegerField(default=0)),
                ('shares', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='daily_stats', to='articles.article')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenancy.site')),
            ],
            options={
                'ordering': ['-day'],
                'indexes': [models.Index(fields=['site', 'day'], name='analytics_d_site_id_2c15ee_idx')],
                'constraints': [models.UniqueConstraint(fields=('site', 'article', 'day'), name='dailystat_unique_site_article_day')],
            },
        ),
    ]
