# Generated by Django 5.1.4 on 2026-08-04 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0004_subcategory_site'),
        ('tenancy', '0002_bootstrap_default_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='depth',
            field=models.PositiveSmallIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='NULL for a root category.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='categories.category'),
        ),
        migrations.AddField(
            model_name='category',
            name='path',
            field=models.CharField(blank=True, db_index=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='category',
            name='url_path',
            field=models.CharField(blank=True, db_index=True, default='', max_length=800),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='mirror_of',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='legacy_mirror', to='categories.category'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['site', 'parent', 'order'], name='categories__site_id_7ec794_idx'),
        ),
    ]
