# Generated by Django 5.1.4 on 2026-08-04 12:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('articles', '0007_article_category_from_tree'),
        ('tenancy', '0002_bootstrap_default_site'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('x', 'X'), ('linkedin', 'LinkedIn'), ('facebook', 'Facebook'), ('threads', 'Threads')], max_length=20)),
                ('provider', models.CharField(default='aggregator', help_text='Registry key of the provider implementation.', max_length=40)),
                ('display_name', models.CharField(max_length=200)),
                ('handle', models.CharField(blank=True, default='', max_length=200)),
                ('avatar_url', models.URLField(blank=True, default='', max_length=500)),
                ('external_id', models.CharField(blank=True, default='', max_length=200)),
                ('encrypted_credentials', models.BinaryField(blank=True, default=b'')),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('connected', 'Connected'), ('expired', 'Token expired'), ('revoked', 'Revoked'), ('error', 'Error')], default='connected', max_length=16)),
                ('status_detail', models.CharField(blank=True, default='', max_length=250)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('connected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenancy.site')),
            ],
            options={
                'ordering': ['platform', 'display_name'],
            },
        ),
        migrations.CreateModel(
            name='SocialPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_label', models.CharField(blank=True, default='', max_length=300)),
                ('state', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('publishing', 'Publishing'), ('published', 'Published'), ('partial', 'Partially published'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='draft', max_length=16)),
                ('scheduled_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='social_posts', to='articles.article')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenancy.site')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='SocialPostTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('x', 'X'), ('linkedin', 'LinkedIn'), ('facebook', 'Facebook'), ('threads', 'Threads')], max_length=20)),
                ('caption', models.TextField(blank=True, default='')),
                ('media', models.JSONField(blank=True, default=list)),
                ('state', models.CharField(choices=[('pending', 'Pending'), ('publishing', 'Publishing'), ('retrying', 'Retrying'), ('published', 'Published'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=16)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('last_error', models.TextField(blank=True, default='')),
                ('external_id', models.CharField(blank=True, default='', max_length=200)),
                ('external_url', models.URLField(blank=True, default='', max_length=500)),
                ('request_snapshot', models.JSONField(blank=True, default=dict)),
                ('response_snapshot', models.JSONField(blank=True, default=dict)),
                ('metrics', models.JSONField(blank=True, default=dict)),
                ('metrics_fetched_at', models.DateTimeField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('next_attempt_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='targets', to='social.socialaccount')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='targets', to='social.socialpost')),
            ],
            options={
                'ordering': ['platform'],
            },
        ),
        migrations.CreateModel(
            name='SocialTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('platform', models.CharField(blank=True, choices=[('x', 'X'), ('linkedin', 'LinkedIn'), ('facebook', 'Facebook'), ('threads', 'Threads')], default='', help_text='Blank means it applies to any platform.', max_length=20)),
                ('body', models.TextField()),
                ('hashtags', models.JSONField(blank=True, default=list)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenancy.site')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddIndex(
            model_name='socialaccount',
            index=models.Index(fields=['site', 'platform', 'status'], name='social_soci_site_id_c8fa8e_idx'),
        ),
        migrations.AddConstraint(
            model_name='socialaccount',
            constraint=models.UniqueConstraint(fields=('site', 'platform', 'external_id'), name='socialaccount_unique_site_platform_external'),
        ),
        migrations.AddIndex(
            model_name='socialpost',
            index=models.Index(fields=['site', 'state', 'scheduled_at'], name='social_soci_site_id_db794c_idx'),
        ),
        migrations.AddIndex(
            model_name='socialposttarget',
            index=models.Index(fields=['state', 'next_attempt_at'], name='social_soci_state_d666b9_idx'),
        ),
        migrations.AddConstraint(
            model_name='socialposttarget',
            constraint=models.UniqueConstraint(fields=('post', 'account'), name='socialtarget_unique_post_account'),
        ),
    ]
