"""Tags: a free-form, cross-cutting taxonomy alongside the category tree.

Hand-rolled rather than ``django-taggit``. Taggit's ``TaggableManager`` is a
custom descriptor that DRF cannot serialize without the unmaintained
``taggit-serializer``, and its ``Tag`` model has nowhere to put the three
things this schema requires of every taxonomy row: a ``site`` FK, a Unicode
slug generated by ``common.slugs`` (taggit calls Django's ``slugify``, which
destroys Bengali -- see that module), and a generic SEO relation. Sixty lines
here buys all three and no dependency.

``TaggedItem`` is a generic through-model rather than an M2M on ``Article`` so
that categories, media and future page types can be tagged by the same
machinery.
"""

from __future__ import annotations

import uuid

from django.contrib.contenttypes.fields import GenericForeignKey
from django.contrib.contenttypes.models import ContentType
from django.db import models, transaction

from apps.seo.models import SEOMixin
from common.slugs import unique_slug
from common.tenancy import TenantModel


class Tag(TenantModel, SEOMixin):
    KIND_CHOICES = (
        ("topic", "Topic"),
        ("series", "Series"),
        ("format", "Format"),
    )

    name = models.CharField(max_length=120)
    slug = models.SlugField(max_length=140, blank=True, allow_unicode=True)
    kind = models.CharField(max_length=16, choices=KIND_CHOICES, default="topic")
    description = models.TextField(blank=True, default="")
    #: Denormalised count of live tagged items, kept fresh by ``recount()``.
    #: Read on every tag list and every public tag page; computing it with a
    #: join would make the taxonomy screen O(tags) queries.
    usage_count = models.PositiveIntegerField(default=0)
    is_active = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        app_label = "taxonomy"
        ordering = ["name"]
        constraints = [
            models.UniqueConstraint(fields=["site", "slug"], name="tag_unique_site_slug"),
            models.UniqueConstraint(fields=["site", "name"], name="tag_unique_site_name"),
        ]
        indexes = [models.Index(fields=["site", "is_active"])]

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = unique_slug(
                self.name,
                Tag.unscoped.filter(site_id=self.site_id).exclude(pk=self.pk),
                fallback=uuid.uuid4().hex[:8],
            )
        super().save(*args, **kwargs)

    def recount(self) -> int:
        count = self.tagged_items.count()
        if count != self.usage_count:
            type(self).unscoped.filter(pk=self.pk).update(usage_count=count)
            self.usage_count = count
        return count

    @transaction.atomic
    def merge_into(self, target: "Tag") -> int:
        """Move every tagged item onto ``target`` and delete this tag.

        Returns the number of items moved. Items already carrying the target
        are dropped rather than re-pointed: the (tag, object) pair is unique,
        so a blind ``update()`` would violate the constraint on exactly the
        articles that carry both -- which is the common case when merging two
        tags that mean the same thing.
        """
        if target.pk == self.pk:
            raise ValueError("Cannot merge a tag into itself.")
        if target.site_id != self.site_id:
            raise ValueError("Tags belong to different sites.")

        already = set(
            TaggedItem.unscoped.filter(tag=target).values_list(
                "content_type_id", "object_id"
            )
        )
        moved = 0
        for item in TaggedItem.unscoped.filter(tag=self):
            if (item.content_type_id, item.object_id) in already:
                item.delete()
            else:
                item.tag = target
                item.save(update_fields=["tag"])
                moved += 1

        self.delete()
        target.recount()
        return moved


class TaggedItem(TenantModel):
    """One (tag, object) edge.

    Carries its own ``site`` for the same reason ``SubCategory`` does: uniform
    one-filter scoping and a uniform SQL-level scoping assertion in tests. The
    value is derived from the tag in ``save()`` so it cannot drift.
    """

    tag = models.ForeignKey(Tag, on_delete=models.CASCADE, related_name="tagged_items")
    content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE)
    object_id = models.PositiveBigIntegerField()
    content_object = GenericForeignKey("content_type", "object_id")
    #: Editor-controlled ordering, so an article can lead with its main topic.
    order = models.PositiveIntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        app_label = "taxonomy"
        ordering = ["order", "id"]
        constraints = [
            models.UniqueConstraint(
                fields=["tag", "content_type", "object_id"],
                name="taggeditem_unique_tag_object",
            )
        ]
        indexes = [
            # The lookup every tagged object makes: "what are my tags?"
            models.Index(fields=["content_type", "object_id"]),
            models.Index(fields=["site", "tag"]),
        ]

    def __str__(self):
        return f"{self.tag} -> {self.content_type}#{self.object_id}"

    def save(self, *args, **kwargs):
        if self.tag_id and not self.site_id:
            self.site_id = self.tag.site_id
        super().save(*args, **kwargs)


def tags_for(obj):
    """Return the ordered tags attached to ``obj``."""
    return Tag.unscoped.filter(
        tagged_items__content_type=ContentType.objects.get_for_model(obj),
        tagged_items__object_id=obj.pk,
    ).order_by("tagged_items__order", "tagged_items__id")


@transaction.atomic
def set_tags(obj, slugs, *, site):
    """Replace ``obj``'s tags with the named ones, creating any that are new.

    Unknown slugs are created rather than rejected: the studio's tag input is a
    combobox where typing a new topic and pressing enter has to work, and a
    404-on-unknown-tag would make that a two-step flow through another screen.
    """
    content_type = ContentType.objects.get_for_model(obj)
    wanted = []
    for position, raw in enumerate(slugs or []):
        name = str(raw).strip()
        if not name:
            continue
        tag = Tag.unscoped.filter(site=site, slug=name).first() or Tag.unscoped.filter(
            site=site, name__iexact=name
        ).first()
        if tag is None:
            tag = Tag.objects.create(site=site, name=name)
        wanted.append((position, tag))

    keep = {tag.pk for _, tag in wanted}
    stale = TaggedItem.unscoped.filter(content_type=content_type, object_id=obj.pk).exclude(
        tag_id__in=keep
    )
    touched = list(stale.values_list("tag_id", flat=True))
    stale.delete()

    for position, tag in wanted:
        TaggedItem.unscoped.update_or_create(
            tag=tag,
            content_type=content_type,
            object_id=obj.pk,
            defaults={"order": position, "site_id": tag.site_id},
        )

    for tag in Tag.unscoped.filter(pk__in=set(touched) | keep):
        tag.recount()
    return [tag for _, tag in wanted]
