import type { Metadata } from "next";
import Link from "next/link";

import { search } from "@/lib/api.server";

/**
 * Server-rendered search.
 *
 * Dynamic, not cached: a result set keyed on an arbitrary query has no reuse
 * worth storing, and a stale search result is worse than a slow one.
 *
 * `noindex` on purpose. Search result pages are the classic thin-content trap
 * — an infinite space of near-duplicate pages generated by whatever anyone
 * types — and letting a crawler into it spends crawl budget that belongs to
 * the articles themselves.
 */

export const dynamic = "force-dynamic";

export const metadata: Metadata = {
  title: "Search",
  robots: { index: false, follow: true },
};

export default async function SearchPage({
  searchParams,
}: {
  searchParams: Promise<{ q?: string; category?: string; tag?: string }>;
}) {
  const params = await searchParams;
  const query = (params.q ?? "").trim();

  const result = query
    ? await search(query, {
        ...(params.category ? { category: params.category } : {}),
        ...(params.tag ? { tag: params.tag } : {}),
      })
    : { query: "", hits: [], total: 0, available: true };

  return (
    <div className="mx-auto max-w-5xl px-4 py-10">
      <h1 className="font-display text-3xl font-bold text-slate-900 dark:text-slate-50">
        Search
      </h1>

      <form action="/search" method="get" className="mt-5 flex gap-2">
        <input
          name="q"
          defaultValue={query}
          placeholder="Search articles, including annotation notes…"
          className="input-field flex-1"
          aria-label="Search articles"
          autoFocus
        />
        <button type="submit" className="btn-primary">
          Search
        </button>
      </form>
      <p className="mt-2 text-xs text-slate-400">
        Annotation text is searchable too — a phrase that only appears inside a
        note will still find its article.
      </p>

      {query && (
        <div className="mt-8">
          {!result.available ? (
            // Not "no results". A reader who searched a real phrase and was
            // told nothing matched will conclude the content does not exist.
            <p className="rounded-xl border border-amber-300 bg-amber-50 p-4 text-sm text-amber-900 dark:border-amber-800 dark:bg-amber-950/40 dark:text-amber-200">
              Search is temporarily unavailable. The articles are all still
              here — try browsing by category while it comes back.
            </p>
          ) : result.total === 0 ? (
            <p className="text-slate-500">
              Nothing matched “{query}”.{" "}
              <Link href="/articles" className="text-primary-600 hover:underline">
                Browse everything
              </Link>
              .
            </p>
          ) : (
            <>
              <p className="mb-4 text-sm text-slate-500">
                {result.total} result{result.total === 1 ? "" : "s"} for “{query}”
              </p>
              <ul className="divide-y divide-slate-100 dark:divide-slate-800">
                {result.hits.map((hit) => (
                  <li key={hit.id} className="py-4">
                    <Link
                      href={`/articles/${encodeURIComponent(hit.path_slug || hit.slug)}`}
                      className="group block"
                    >
                      <h2 className="font-display text-lg font-semibold text-slate-900 group-hover:text-primary-700 dark:text-slate-100 dark:group-hover:text-primary-300">
                        {hit.title}
                      </h2>
                      <p className="mt-1 line-clamp-2 text-sm text-slate-600 dark:text-slate-400">
                        {hit.excerpt}
                      </p>
                      <p className="mt-1.5 flex flex-wrap items-center gap-2 text-xs text-slate-400">
                        {hit.category && <span>{hit.category}</span>}
                        {hit.reading_time > 0 && <span>{hit.reading_time} min read</span>}
                        {hit.tags?.slice(0, 3).map((tag) => (
                          <span key={tag} className="rounded bg-slate-100 px-1.5 dark:bg-slate-800">
                            {tag}
                          </span>
                        ))}
                      </p>
                    </Link>
                  </li>
                ))}
              </ul>
            </>
          )}
        </div>
      )}
    </div>
  );
}
