# Generated by Django 5.1.4 on 2026-04-12 14:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("categories", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=300)),
                ("slug", models.SlugField(blank=True, max_length=300, unique=True)),
                ("content", models.JSONField(default=dict, help_text="Editor.js block content stored as JSON")),
                ("excerpt", models.TextField(blank=True, default="", max_length=500)),
                ("featured_image", models.URLField(blank=True, default="")),
                ("status", models.CharField(choices=[("draft", "Draft"), ("published", "Published"), ("archived", "Archived")], default="draft", max_length=10)),
                ("is_featured", models.BooleanField(default=False)),
                ("reading_time", models.PositiveIntegerField(default=0, help_text="Estimated reading time in minutes")),
                ("views_count", models.PositiveIntegerField(default=0)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("author", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="articles", to=settings.AUTH_USER_MODEL)),
                ("category", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="articles", to="categories.category")),
                ("subcategory", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="articles", to="categories.subcategory")),
            ],
            options={
                "ordering": ["-published_at", "-created_at"],
            },
        ),
    ]
