# Generated by Django 5.1.4

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0007_article_category_from_tree"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="article",
            index=models.Index(
                fields=["site", "is_live", "-published_at"],
                name="article_site_live_pub",
            ),
        ),
        migrations.AddIndex(
            model_name="article",
            index=models.Index(
                fields=["site", "status", "-updated_at"],
                name="article_site_status_upd",
            ),
        ),
        migrations.AddIndex(
            model_name="article",
            index=models.Index(fields=["site", "slug"], name="article_site_slug"),
        ),
        migrations.AddIndex(
            model_name="article",
            index=models.Index(
                fields=["author", "status"], name="article_author_status"
            ),
        ),
    ]
