# Generated by Django 5.1.4 on 2026-08-04 02:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('articles', '0004_add_site'),
        ('tenancy', '0002_bootstrap_default_site'),
    ]

    operations = [
        migrations.CreateModel(
            name='Placement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path_slug', models.SlugField(allow_unicode=True, help_text="URL slug on this site; may differ from the article's own slug.", max_length=300)),
                ('is_primary', models.BooleanField(default=False, help_text="True for the owning site's placement.")),
                ('is_live', models.BooleanField(db_index=True, default=False)),
                ('canonical_to_primary', models.BooleanField(default=True, help_text='Point rel=canonical at the owning site rather than self.')),
                ('override_title', models.CharField(blank=True, default='', max_length=300)),
                ('override_excerpt', models.TextField(blank=True, default='', max_length=500)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.IntegerField(default=0, help_text='Manual curation order.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placements', to='articles.article')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placements', to='tenancy.site')),
            ],
            options={
                'ordering': ['order', '-published_at'],
                'indexes': [models.Index(fields=['site', 'is_live', '-published_at'], name='syndication_site_id_446334_idx')],
                'constraints': [models.UniqueConstraint(fields=('article', 'site'), name='placement_unique_article_site'), models.UniqueConstraint(fields=('site', 'path_slug'), name='placement_unique_site_path'), models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('article',), name='placement_single_primary')],
            },
        ),
    ]
