# Generated by Django 5.1.4 on 2026-08-04 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_article_category_from_tree'),
        ('syndication', '0002_backfill_primary_placements'),
        ('tenancy', '0002_bootstrap_default_site'),
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('kind', models.CharField(choices=[('site', 'Owned site'), ('partner_api', 'Partner API'), ('webhook', 'Webhook'), ('rss', 'RSS feed'), ('newsletter', 'Newsletter')], default='webhook', max_length=20)),
                ('endpoint_url', models.URLField(blank=True, default='', max_length=500)),
                ('secret', models.CharField(blank=True, default='', max_length=128)),
                ('headers', models.JSONField(blank=True, default=dict, help_text='Extra static headers to send.')),
                ('events', models.JSONField(blank=True, default=list, help_text='Event names to deliver; empty means all.')),
                ('is_active', models.BooleanField(default=True)),
                ('disabled_at', models.DateTimeField(blank=True, null=True)),
                ('disabled_reason', models.CharField(blank=True, default='', max_length=250)),
                ('consecutive_failures', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('site', models.ForeignKey(help_text='The tenant that owns this destination.', on_delete=django.db.models.deletion.CASCADE, related_name='destinations', to='tenancy.site')),
                ('target_site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inbound_destinations', to='tenancy.site')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ContentDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_label', models.CharField(blank=True, default='', max_length=300)),
                ('event', models.CharField(choices=[('publish', 'Published'), ('update', 'Updated'), ('unpublish', 'Unpublished'), ('delete', 'Deleted')], default='publish', max_length=16)),
                ('state', models.CharField(choices=[('pending', 'Pending'), ('delivering', 'Delivering'), ('delivered', 'Delivered'), ('failed', 'Failed'), ('abandoned', 'Abandoned'), ('skipped', 'Skipped')], db_index=True, default='pending', max_length=16)),
                ('idempotency_key', models.CharField(db_index=True, max_length=64, unique=True)),
                ('event_id', models.CharField(db_index=True, max_length=36)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('next_attempt_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('last_error', models.TextField(blank=True, default='')),
                ('response_status', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('payload_snapshot', models.JSONField(blank=True, default=dict)),
                ('response_snapshot', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries', to='articles.article')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='syndication.destination')),
            ],
            options={
                'verbose_name_plural': 'Content deliveries',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='destination',
            index=models.Index(fields=['site', 'is_active'], name='syndication_site_id_e21614_idx'),
        ),
        migrations.AddConstraint(
            model_name='destination',
            constraint=models.UniqueConstraint(fields=('site', 'name'), name='destination_unique_site_name'),
        ),
        migrations.AddIndex(
            model_name='contentdelivery',
            index=models.Index(fields=['destination', 'state'], name='syndication_destina_f8b59d_idx'),
        ),
        migrations.AddIndex(
            model_name='contentdelivery',
            index=models.Index(fields=['state', 'next_attempt_at'], name='syndication_state_91448a_idx'),
        ),
    ]
