# Generated by Django 5.1.4 on 2026-08-04 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('articles', '0007_article_category_from_tree'),
        ('tenancy', '0002_bootstrap_default_site'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndexingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_pk', models.PositiveBigIntegerField()),
                ('action', models.CharField(choices=[('upsert', 'Upsert'), ('delete', 'Delete')], default='upsert', max_length=10)),
                ('state', models.CharField(choices=[('pending', 'Pending'), ('indexed', 'Indexed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=10)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('last_error', models.TextField(blank=True, default='')),
                ('content_hash', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='indexing_logs', to='articles.article')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenancy.site')),
            ],
            options={
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['state', 'updated_at'], name='search_inde_state_00cbdf_idx')],
                'constraints': [models.UniqueConstraint(fields=('site', 'article_pk', 'action'), name='indexinglog_unique_site_article_action')],
            },
        ),
    ]
