# Generated by Django 5.1.4 on 2026-08-04 03:34

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('articles', '0004_add_site'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('tenancy', '0002_bootstrap_default_site'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SEOAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField(default=0)),
                ('readability_score', models.PositiveSmallIntegerField(default=0)),
                ('checks', models.JSONField(default=list)),
                ('content_hash', models.CharField(blank=True, default='', max_length=64)),
                ('computed_at', models.DateTimeField(auto_now=True)),
                ('article', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seo_analysis', to='articles.article')),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenancy.site')),
            ],
            options={
                'verbose_name_plural': 'SEO analyses',
            },
        ),
        migrations.CreateModel(
            name='Redirect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_path', models.CharField(help_text='Always a leading slash, no host.', max_length=500)),
                ('target_path', models.CharField(max_length=500)),
                ('status_code', models.PositiveSmallIntegerField(choices=[(301, '301 Permanent'), (302, '302 Found'), (307, '307'), (308, '308')], default=301)),
                ('is_regex', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('hit_count', models.PositiveIntegerField(default=0)),
                ('last_hit_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.CharField(blank=True, default='', max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redirects', to='tenancy.site')),
            ],
            options={
                'ordering': ['source_path'],
                'indexes': [models.Index(fields=['site', 'is_active', 'source_path'], name='seo_redirec_site_id_4af160_idx')],
                'constraints': [models.UniqueConstraint(fields=('site', 'source_path'), name='redirect_unique_site_source')],
            },
        ),
        migrations.CreateModel(
            name='SEOMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveBigIntegerField()),
                ('meta_title', models.CharField(blank=True, default='', max_length=200)),
                ('meta_description', models.TextField(blank=True, default='', max_length=320)),
                ('canonical_url', models.URLField(blank=True, default='', max_length=500)),
                ('focus_keyword', models.CharField(blank=True, default='', max_length=120)),
                ('secondary_keywords', models.JSONField(blank=True, default=list)),
                ('robots_index', models.BooleanField(default=True)),
                ('robots_follow', models.BooleanField(default=True)),
                ('robots_noarchive', models.BooleanField(default=False)),
                ('robots_nosnippet', models.BooleanField(default=False)),
                ('robots_noimageindex', models.BooleanField(default=False)),
                ('max_snippet', models.IntegerField(default=-1, help_text='-1 = unset')),
                ('max_image_preview', models.CharField(choices=[('none', 'none'), ('standard', 'standard'), ('large', 'large')], default='large', max_length=8)),
                ('max_video_preview', models.IntegerField(default=-1)),
                ('unavailable_after', models.DateTimeField(blank=True, null=True)),
                ('og_title', models.CharField(blank=True, default='', max_length=200)),
                ('og_description', models.TextField(blank=True, default='', max_length=400)),
                ('og_image', models.URLField(blank=True, default='', max_length=500)),
                ('og_image_alt', models.CharField(blank=True, default='', max_length=250)),
                ('og_type', models.CharField(default='article', max_length=32)),
                ('og_locale', models.CharField(blank=True, default='', max_length=10)),
                ('twitter_card', models.CharField(choices=[('summary', 'summary'), ('summary_large_image', 'summary_large_image'), ('player', 'player')], default='summary_large_image', max_length=24)),
                ('twitter_title', models.CharField(blank=True, default='', max_length=200)),
                ('twitter_description', models.TextField(blank=True, default='', max_length=400)),
                ('twitter_image', models.URLField(blank=True, default='', max_length=500)),
                ('twitter_site', models.CharField(blank=True, default='', max_length=40)),
                ('schema_type', models.CharField(choices=[('Article', 'Article'), ('BlogPosting', 'BlogPosting'), ('NewsArticle', 'NewsArticle'), ('HowTo', 'HowTo')], default='Article', max_length=40)),
                ('structured_data_overrides', models.JSONField(blank=True, default=dict, help_text='Deep-merged over the generated JSON-LD, last.')),
                ('faq_items', models.JSONField(blank=True, default=list, help_text='[{q, a}, ...]')),
                ('hide_from_sitemap', models.BooleanField(default=False)),
                ('sitemap_priority', models.DecimalField(decimal_places=1, default=Decimal('0.7'), max_digits=2)),
                ('sitemap_changefreq', models.CharField(default='weekly', max_length=12)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('site', models.ForeignKey(blank=True, help_text='NULL = default for every site; set = override for that site.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seo_overrides', to='tenancy.site')),
            ],
            options={
                'verbose_name': 'SEO metadata',
                'verbose_name_plural': 'SEO metadata',
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='seo_seometa_content_a438cb_idx')],
                'constraints': [models.UniqueConstraint(fields=('content_type', 'object_id', 'site'), name='seo_unique_object_site'), models.UniqueConstraint(condition=models.Q(('site__isnull', True)), fields=('content_type', 'object_id'), name='seo_unique_object_default')],
            },
        ),
    ]
